#!/usr/bin/env python3
"""HPCA 2027 revision: ideal load fusion, Golden Cove ROB 352 vs ROB 512.

Workloads: Helios SPEC CPU2017 speed_int fixed-region traces
  (huggingface.co/datasets/harry1332/helios-spec2017-fixed-region-20261002)
Methodology (matches Helios): 500M instructions from instruction 1, no warmup.

Ideal fusion runs in two passes per ROB size:
  pass 1  logs every fusible LOAD1/LOAD2 pair within a window equal to the ROB
          size. Pass 1 does not change timing, so it is also the no-fusion
          baseline.
  pass 2  replays those pairs and models their fusion.

Usage (from the scarab-infra root):
  ./json/hpca2027-revision/helios_ideal_fusion.py run       # register traces, pass 1, pass 2
  ./json/hpca2027-revision/helios_ideal_fusion.py status
  ./json/hpca2027-revision/helios_ideal_fusion.py package   # -> scarab/results/hpca2027-revision-ideal-fusion/

  --robs 512 runs only ROB 512 (default: 352 512). CANDIDATES_DIR=<dir>
  puts the pass-1 candidate logs elsewhere (e.g. tmpfs).

Pass-1 candidates are kept gzip-compressed (~1 GB each) on disk at
CANDIDATES_DIR/rob<N>/<benchmark>/20.csv.gz, outside tmpfs. Raw simulation
output: <scarab>/src/simulations/helios_spec17_ideal_fusion_pass<P>_rob<N>/.
--inst-limit and --tag run a short smoke test in separate directories.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
from pathlib import Path

INFRA_DIR = Path(__file__).resolve().parents[2]
DESCRIPTOR_DIR = "hpca2027-revision"

SCARAB_PATH = Path(os.environ.get("SCARAB_PATH", Path.home() / "scarab"))
TRACES_DIR = Path("/dev/shm/baseline")
CANDIDATES_DIR = Path(os.environ.get("CANDIDATES_DIR", Path.home() / "ideal_fusion_candidates"))
# CANDIDATES_DIR is bind-mounted here inside the simulation container (as the
# descriptor's application_dir).
CANDIDATES_MOUNT = Path("/tmp_home/application")
RESULTS_DIR = SCARAB_PATH / "results" / "hpca2027-revision-ideal-fusion"

SUITE = "spec2017"
SUBSUITE = "speed_int_helios"
APPS = ["gcc_s", "gcc_s_2", "gcc_s_3", "leela_s", "mcf_s", "omnetpp_s", "xalancbmk_s"]
CLUSTER_ID = "20"
ROB_SIZES = [352, 512]
INST_LIMIT = 500_000_000
EXPERIMENT = "helios_spec17_ideal_fusion"
PASS_LABELS = {1: "baseline", 2: "ideal-fusion"}


def sci(*args: str) -> None:
    print(f"$ ./sci {' '.join(args)}", flush=True)
    rc = subprocess.run(["./sci", *args], cwd=INFRA_DIR).returncode
    if rc != 0:
        sys.exit(f"./sci {' '.join(args)} exited {rc}")


def config_name(pass_num: int, rob: int, tag: str = "") -> str:
    # sci writes each config to simulations/<config>/, so the name carries the
    # pass to keep pass 1 and pass 2 output apart.
    return f"{tag}{EXPERIMENT}_pass{pass_num}_rob{rob}"


def descriptor_name(pass_num: int, tag: str = "") -> str:
    return f"{DESCRIPTOR_DIR}/{tag}helios_ideal_fusion_pass{pass_num}"


def descriptor(pass_num: int, inst_limit: int, tag: str) -> dict:
    configs = {}
    for rob in ROB_SIZES:
        log = CANDIDATES_MOUNT / f"{tag}rob{rob}" / "{workload}" / "{cluster_id}.csv.gz"
        configs[config_name(pass_num, rob, tag)] = {
            "params": (f"--inst_limit {inst_limit} --node_table_size {rob} "
                       f"--ideal_fusion_pass {pass_num} --ideal_fusion_distance {rob} "
                       f"--ideal_fusion_log {log}"),
            "binary": "scarab_current",
            "slurm_options": "",
            "memory_overhead_mb": 0,
        }
    return {
        "descriptor_type": "simulation",
        "architecture": "golden_cove",
        "experiment": f"{tag}{EXPERIMENT}_pass{pass_num}",
        "workload_manager": "manual",
        "root_dir": str(SCARAB_PATH / "src"),
        "application_dir": str(CANDIDATES_DIR),
        "scarab_path": str(SCARAB_PATH),
        "scarab_build": "opt",
        "traces_dir": str(TRACES_DIR),
        "top_simpoint": False,
        "_comment": (f"Ideal load fusion pass {pass_num} "
                     f"({'log candidates; no-fusion baseline' if pass_num == 1 else 'model fusion'}), "
                     "Golden Cove ROB 352 vs 512, fusion window = ROB size. Helios SPEC2017 speed_int "
                     "fixed-region traces; 500M instructions from instruction 1, no warmup. "
                     "Generated by helios_ideal_fusion.py."),
        "simulations": [{
            "suite": SUITE, "subsuite": SUBSUITE, "workload": APPS,
            "cluster_id": None, "simulation_type": "memtrace", "warmup": 0,
        }],
        "configurations": configs,
        "collect_stats": {"configs": None},
        "visualize": {"baseline": next(iter(configs)), "configs": list(configs), "counters": ["IPC"]},
        "mem": {"collection_baseline": None, "fallback_mb": 4096},
    }


def run(inst_limit: int, tag: str) -> None:
    subprocess.run([str(INFRA_DIR / "json" / DESCRIPTOR_DIR / "baseline.sh"), "--register"], check=True)
    CANDIDATES_DIR.mkdir(parents=True, exist_ok=True)
    for pass_num in (1, 2):
        path = INFRA_DIR / "json" / f"{descriptor_name(pass_num, tag)}.json"
        path.write_text(json.dumps(descriptor(pass_num, inst_limit, tag), indent=2) + "\n")

    # `--sim` (re)builds scarab_current from the scarab repo's git HEAD as needed.
    # Pass 2 reads the candidate files pass 1 writes, so the passes run in order.
    for pass_num in (1, 2):
        sci("--sim", descriptor_name(pass_num, tag))
        sci("--collect-stats", descriptor_name(pass_num, tag))


def status() -> None:
    for pass_num in (1, 2):
        sci("--status", descriptor_name(pass_num))


# --------------------------------------------------------------------------- #
# Packaging
# --------------------------------------------------------------------------- #
KEEP_SUFFIXES = (".stat.0.csv",)


def read_csv_stats(path: Path) -> dict:
    stats = {}
    with path.open() as f:
        for row in csv.reader(f):
            if len(row) >= 3:
                try:
                    stats[row[0].strip()] = int(row[2].strip())
                except ValueError:
                    pass
    return stats


def geomean(xs):
    return math.exp(sum(math.log(x) for x in xs) / len(xs))


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def copy_run(run_dir: Path, dest: Path) -> None:
    dest.mkdir(parents=True)
    for f in sorted(run_dir.iterdir()):
        if f.name.endswith(KEEP_SUFFIXES) or f.name == "PARAMS.out":
            shutil.copy2(f, dest / f.name)
    # Heartbeat lines make sim.log ~26 MB at 500M instructions; keep the rest.
    with (run_dir / "sim.log").open(errors="replace") as src, (dest / "sim.log").open("w") as out:
        out.writelines(l for l in src if not l.startswith("** Heartbeat"))


def package() -> int:
    sim_root = SCARAB_PATH / "src" / "simulations"
    stats, problems = {}, []
    for rob in ROB_SIZES:
        for pass_num in (1, 2):
            for app in APPS:
                run_dir = sim_root / config_name(pass_num, rob) / app / CLUSTER_ID
                if not (run_dir / "core.stat.0.csv").is_file():
                    problems.append(f"{config_name(pass_num, rob)}/{app}: run missing or unfinished")
                    continue
                s = read_csv_stats(run_dir / "core.stat.0.csv")
                s.update(read_csv_stats(run_dir / "ideal_fusion.stat.0.csv"))
                if s["Cumulative_Instructions"] < INST_LIMIT:
                    problems.append(f"{config_name(pass_num, rob)}/{app}: only "
                                    f"{s['Cumulative_Instructions']:,} instructions")
                stats[rob, pass_num, app] = (s, run_dir)
    if problems:
        print("Cannot package results:")
        for p in problems:
            print(f"  - {p}")
        return 1

    if RESULTS_DIR.exists():
        shutil.rmtree(RESULTS_DIR)
    for (rob, pass_num, app), (_, run_dir) in stats.items():
        copy_run(run_dir, RESULTS_DIR / f"rob-{rob}" / PASS_LABELS[pass_num] / app)

    def ipc(rob, pass_num, app):
        s = stats[rob, pass_num, app][0]
        return s["Cumulative_Instructions"] / s["Cumulative_Cycles"]

    rows = []
    for app in APPS:
        for rob in ROB_SIZES:
            base, fused = ipc(rob, 1, app), ipc(rob, 2, app)
            s2 = stats[rob, 2, app][0]
            rows.append({
                "benchmark": app, "rob": rob, "ipc_baseline": base, "ipc_ideal_fusion": fused,
                "speedup": fused / base,
                "fused_load_pct": 100 * s2["IDEAL_FUSION_LOADS_PARTICIPATED"] / s2["ONPATH_MEM_LOADS"],
            })
    gm = {rob: (geomean([r["ipc_baseline"] for r in rows if r["rob"] == rob]),
                geomean([r["ipc_ideal_fusion"] for r in rows if r["rob"] == rob]))
          for rob in ROB_SIZES}

    with (RESULTS_DIR / "summary.csv").open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["benchmark", "rob", "ipc_baseline", "ipc_ideal_fusion",
                    "ideal_fusion_speedup", "loads_fused_pct"])
        for r in rows:
            w.writerow([r["benchmark"], r["rob"], f"{r['ipc_baseline']:.4f}", f"{r['ipc_ideal_fusion']:.4f}",
                        f"{r['speedup']:.4f}", f"{r['fused_load_pct']:.2f}"])
        for rob in ROB_SIZES:
            w.writerow(["geomean", rob, f"{gm[rob][0]:.4f}", f"{gm[rob][1]:.4f}",
                        f"{gm[rob][1] / gm[rob][0]:.4f}", ""])

    with (RESULTS_DIR / "candidates.csv").open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["rob", "benchmark", "file", "bytes", "sha256"])
        for rob in ROB_SIZES:
            for app in APPS:
                p = CANDIDATES_DIR / f"rob{rob}" / app / f"{CLUSTER_ID}.csv.gz"
                w.writerow([rob, app, f"rob{rob}/{app}/{p.name}", p.stat().st_size, sha256(p)])

    by = {(r["benchmark"], r["rob"]): r for r in rows}
    table = "\n".join(
        "| " + app + " | " + " | ".join(
            f"{by[app, rob]['ipc_baseline']:.3f} | {by[app, rob]['ipc_ideal_fusion']:.3f} | "
            f"{(by[app, rob]['speedup'] - 1) * 100:+.2f}% | {by[app, rob]['fused_load_pct']:.1f}%"
            for rob in ROB_SIZES) + " |"
        for app in APPS)
    gm_row = "| **Geomean** | " + " | ".join(
        f"**{gm[rob][0]:.3f}** | **{gm[rob][1]:.3f}** | **{(gm[rob][1] / gm[rob][0] - 1) * 100:+.2f}%** | "
        for rob in ROB_SIZES) + " |"
    head = " | ".join(f"Base {r} | Ideal {r} | Speedup {r} | Fused {r}" for r in ROB_SIZES)
    align = "|---" + "|---:" * 4 * len(ROB_SIZES) + "|"
    opts = "" if ROB_SIZES == [352, 512] else " --robs " + " ".join(map(str, ROB_SIZES))
    env = f"CANDIDATES_DIR={CANDIDATES_DIR} " if CANDIDATES_DIR != Path.home() / "ideal_fusion_candidates" else ""
    rerun = "\n".join(f"{env}./json/hpca2027-revision/helios_ideal_fusion.py {step}{opts}{c}" for step, c in
                       (("run", "       # register traces, pass 1, pass 2"), ("status", ""),
                        ("package", "   # regenerate this directory")))
    robs_title = " vs ".join(str(r) for r in ROB_SIZES)
    rob_rows = "\n".join(
        f"| ROB {r} | Golden Cove as-is (`--node_table_size {r}`) |" if r == 512 else
        f"| ROB {r} | Golden Cove with `--node_table_size {r}`; nothing else changed |"
        for r in ROB_SIZES)
    windows = " / ".join(str(r) for r in ROB_SIZES)
    layout = "\n".join(
        f"rob-{r}/baseline/<benchmark>/       pass 1: Scarab stats (*.stat.0.csv), PARAMS.out, sim.log\n"
        f"rob-{r}/ideal-fusion/<benchmark>/   pass 2: same"
        for r in ROB_SIZES)

    readme = f"""# HPCA 2027 revision: ideal load fusion, Golden Cove ROB {robs_title}

## Setup

| | |
|---|---|
| Core | Golden Cove (`src/PARAMS.golden_cove`) |
{rob_rows}
| Fusion | Ideal load-load fusion: two on-path loads to the same 64 B cache block, with no intervening store to it, within a window equal to the ROB size ({windows} µops). Each load fuses at most once; a LOAD2 pairs with the oldest eligible LOAD1 |
| Workloads | SPEC CPU2017 speed_int, Helios fixed-region traces ([dataset](https://huggingface.co/datasets/harry1332/helios-spec2017-fixed-region-20261002)) |
| Window | {INST_LIMIT // 1_000_000}M instructions from instruction 1, no warmup (Helios methodology) |
| Scarab branch | `hpca2027-revision-ideal-fusion` |
| Launcher | scarab-infra `hpca2027-revision`: `json/hpca2027-revision/helios_ideal_fusion.py` |

Ideal fusion runs in two passes. **Pass 1** logs every fusible pair and does not
change timing, so its IPC is the no-fusion **baseline**. **Pass 2** replays the
pairs: the younger load (LOAD2) takes no ROB, LSQ or RS entry and gets its value
when the older load (LOAD1) completes.

## IPC

| Benchmark | {head} |
{align}
{table}
{gm_row}

- IPC = `Cumulative_Instructions / Cumulative_Cycles` from `core.stat.0.csv`.
- Speedup = ideal-fusion IPC / baseline IPC at the same ROB size.
- Fused = share of retired on-path loads that took part in a fused pair
  (`IDEAL_FUSION_LOADS_PARTICIPATED / ONPATH_MEM_LOADS`).
- Machine-readable copy: [`summary.csv`](summary.csv).

## Layout

```
{layout}
summary.csv                       IPC, speedup and fused-load share per benchmark
candidates.csv                    size and SHA-256 of each pass-1 candidate log
```

`sim.log` files have their heartbeat lines removed.

## Fusion candidates

Pass 1 writes one gzip-compressed CSV per benchmark and ROB size
(`rob<N>/<benchmark>/20.csv.gz`, one row per fused pair: PCs, addresses, sizes
and dynamic µop numbers of LOAD1 and LOAD2). They are too large for git and
are kept outside the repo; `candidates.csv` lists their checksums.

## Reproduce

```bash
cd ~/scarab && git checkout hpca2027-revision-ideal-fusion
cd ~/scarab-infra && git checkout hpca2027-revision
{rerun}
```
"""
    (RESULTS_DIR / "README.md").write_text(readme)
    print(f"Packaged {len(APPS)} benchmarks x {len(ROB_SIZES)} ROB sizes x 2 passes into {RESULTS_DIR}")
    for rob in ROB_SIZES:
        print(f"ROB {rob}: geomean IPC {gm[rob][0]:.4f} -> {gm[rob][1]:.4f} "
              f"({(gm[rob][1] / gm[rob][0] - 1) * 100:+.2f}%)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("step", choices=["run", "status", "package"])
    ap.add_argument("--inst-limit", type=int, default=INST_LIMIT)
    ap.add_argument("--tag", default="", help="prefix for experiment and candidate dirs (e.g. smoke_)")
    ap.add_argument("--robs", type=int, nargs="+", default=ROB_SIZES, help="ROB sizes to run (default: 352 512)")
    a = ap.parse_args()
    ROB_SIZES[:] = a.robs
    if a.step == "run":
        run(a.inst_limit, a.tag)
    elif a.step == "status":
        status()
    else:
        return package()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
